INSERT INTO Disc (name, genre, price) VALUES ('Pop Out feat. Lil Tjay', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Food', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Phantom Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('POP/STARS', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('50 Pop Sensations', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Evil', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('pop a pill', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('80s Pop Number 1s', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop 2', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('80s Pop Hits', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('PTX Presents: Top Pop, Vol. I', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dont Feed The Pop Monster', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 4', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 6', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('THIS IS... ICONA POP', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dark Holler Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Psychology', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 7', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Star', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('UP', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Onyx', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Lust For Life', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 5', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Style', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 2', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop, Vol. 3', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop 5', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Awkward Pop Songs', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('70s Pop Number 1s', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('I Love It', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Shake It Off: Instrumental Guitar Covers of Pop Hits', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('City Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Pop Rock Solo Piano', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Current Pop Hits: Instrumental Versions', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Weekend', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Waking Lions', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Culture', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Joyas Prestadas - Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The Stooges', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Planet Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Music', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Porn', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Up', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Therapy', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Zest Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop! The First 20 Hits', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Pop Life', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('El Templo del Pop', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Lipstick On The Mirror', 1, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Brasil MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB 2', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mpb em Cena (Ao Vivo)', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mpb Pras Crianças', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('20 Grandes Sucessos De Quarteto Em Cy & Mpb-4', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The Best of Brazilian MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Cicatrizes', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Brazil - Mpb And Bossa Nova', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Acústico', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('40 anos de música (ao vivo)', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Instrumental, Vol. 1', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Grandes mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB-4', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Acústico MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB em Cy', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Instrumental, Vol. 3', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Instrumental, Vol. 2', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Brazilian Modern Popular Music (MPB)', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Amigo É Pra Essas Coisas - Ao Vivo', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Deixa Estar', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('O Sonho, a Vida, a Roda Viva! 50 Anos (Ao Vivo)', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mpb Brazil: Brazil, Samba, Bossa Nova And Beyond / A Nova Canção Brasileira', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB!', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Unplugged MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Eletro MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Fundamental - Mpb', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Versões Mpb', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('FINO MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Acústico Mpb', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Especial Mpb', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Reggae', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Nesse MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mpb Acústico', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Acústico', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB Connections', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('FINO MPB 2', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB em Chorinho', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('MPB de Rua', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Gospel e Mpb', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mestres da MPB', 2, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The New Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The New Classic (Deluxe Version)', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Man', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Chris Ledoux', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Rock', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic (feat. POWERS)', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Songs for Kids: Classic Childrens Music', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Pop Rock Solo Piano', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('OCCULT CLASSIC', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Punk Goes Classic Rock', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Sinatra - His Great Performances 1953-1960', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Total Reggae: Classic Roots', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('40 Classic Video Game Songs', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Man (Remix)', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Stone Cold Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('50 Classic Rock Favorites', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Williams -- Romance of the Guitar', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Rock Radio', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Sleep Baby Sleep: Classic Childrens Bedtime Lullabies', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Cult Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dream a Little Dream: Classic Piano Lullabies', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Piano Magic Classic Movie Themes', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The New Classic Trio', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Nursery Rhymes: Piano Lullabies', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Man', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classical Lullabies: Classic Piano for Babies', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Cash Hall Of Fame Series', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('More Songs for Kids: Classic Childrens Music', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('My Classic Memories of You', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Country - Bar Room Favorites', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Laurie Berkners Favorite Classic Kids Songs', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('20 Classic Piano Movie Themes', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Duets An American Classic', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Reggae', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('60s Classic Hits', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Vintage Ibiza Classic Vol. 1', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Best of Baby Beethoven Classic Music Box', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Masters', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Low & Slow (Classic Low Rider Jams)', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Capitol Years Box Set - Classic Album Collection', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('ALT CLASSIC', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Rock 70s', 3, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('TrapStar Turnt PopStar', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Cross Me (feat. Chance the Rapper & PnB Rock)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Redemption', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Save Rock And Roll', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Combat Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('GTTM: Goin Thru the Motions', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Catch These Vibes', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock N Roll Jesus', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Camp Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('TrapStar Turnt PopStar (Deluxe)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Kings Dead (with Kendrick Lamar, Future & James Blake)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Horses (with PnB Rock, Kodak Black & A Boogie Wit da Hoodie)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The Rolling Stones Rock And Roll Circus (Expanded)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Save Rock And Roll', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Camp Rock 2: The Final Jam', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dutty Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Devil Without A Cause', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Cocky', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Lovers Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock Steady', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Party Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Elvis Golden Records', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dutty Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Life on a Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Country Is My Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('I Love Rock N Roll (Expanded Edition)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Blue Hawaii', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Elvis 30 #1 Hits', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('RNB3', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Classic Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Let There Be Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Three Chord Country and American Rock & Roll', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('90059', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock Of The 80s', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The Impossible Kid', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock or Bust', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Follow Me Home', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Don`t Rock The Jukebox', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock N Roll Rarities', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Rock and Roll Night Club', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dirt Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Crunk Rock (Deluxe)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Mecca And The Soul Brother', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Born Free', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Leave Em Alone (with Lil Baby & City Girls feat. PnB Rock)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Kid Rock', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('The 3rd Wish: To Rock The World (Explicit)', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('Dirtbagz, Vol. 1', 4, random() * 100);
INSERT INTO Disc (name, genre, price) VALUES ('First Kiss', 4, random() * 100);